application:
  #应用名称：当使用到微服务配置中心时，name必须和对应应用匹配
  name: hello-aas-ams

#日志打印配置
logging:
  config: classpath:logback-spring.xml

#server配置参数
server:
  port: 8088
spring:
  datasource:
    aasDs:
      name: aas-mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullNamePatternMatchesAll=true&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true
      username: root
      password: 11111111
      initialSize: 5
      maxActive: 20
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      filters: stat,wall
#aas框架配置参数
aas:
  #是否启用蜂巢监控
  amc:
    enabled: true
  #swagger插件配置
  swagger:
    enabled: true
  #eureka:
    #registry:
      #enabled: true
    #serviceUrl: http://192.168.230.130:1001/eureka
    #instance:
      #leaseExpirationDurationInSeconds: 30
      #leaseRenewalIntervalInSeconds: 90
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.230.130:1001/eureka
    enabled: false
dubbo:
  application:
    name: ${application.name}
  registry:
    address: zookeeper://192.168.3.131:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
  reference:
    check: false